name: Daily Box Bot Debug
on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'WARNIN'
        type: choice
        options:
        - INFO
        - WARNIN
        - DEBUG
      tags:
        description: 'Test scenario tags'
        required: false
        type: boolean
      environment:
        description: 'Environment to run tests against'
        type: environment
        required: true

jobs:
  Dialy-Box-Bot-Actions-Debug:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
        with:
          persist-credentials: false
          fetch-depth: 0
      - name: List files in the repository
        run: |
          echo "Log level: $LOGLEVEL"
          echo "Tags: $TAGS"
          echo "Environment: $ENVIRONMENT"
          ls ${{ github.workspace }}
        env:
          LOGLEVEL: ${{ inputs.logLevel }}
          TAGS: ${{ inputs.tags }}
          ENVIRONMENT: ${{ inputs.environment }}
      - name: Setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - run: pip install feedparser requests dateparser
      - name: Run script
        run: python main.py
