name: RSS Daily
on: 
  schedule:
    - cron:  '0 20 * * *'
  push:
    branches:
      main
jobs:
  RSS-Dialy-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
        with:
          persist-credentials: false
          fetch-depth: 0
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - name: Setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - run: pip install feedparser
      - name: Run script
        run: python sjmy.py
      - name: Commit
        run: |
          git config --local user.email 'huzhifeng@qq.com'
          git config --local user.username 'Zhifeng Hu'
          git commit -a -m "Add changes"
      - name: Push
        uses: ad-m/github-push-action@master
        with: 
          github_token: ${{ secrets.SJMY }}
          branch: ${{ github.ref }}
        
