name: RSS Daily
on: 
  schedule:
    - cron:  '0 20 * * *'
  push:
    branches:
      main
jobs:
  RSS-Dialy-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - name: Setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - run: pip install feedparser
      - name: Run script
        run: python sjmy.py
      - name: Commit
        env: 
          USER: ${{ secrets.USER }}
          PASSWORD: ${{ secrets.PASSWORD }}
          HOST: ${{ secrets.HOST }}
        run: |
          git config --global user.email huzhifeng@qq.com
          git config --global user.username huzhifeng
          git add .
          git commit -m "update" -a
          git push
        
